export default {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',

  // account actions
  ACCOUNT_SERVICES_GET: 'ACCOUNT_SERVICES_GET',
  DASHBOARD_PAGE_LOADED: 'DASHBOARD_PAGE_LOADED',
  ACCOUNT_UPDATE_DETAILS: 'ACCOUNT_UPDATE_DETAILS',
  SERVICE_OVERVIEW_PAGE_LOADED: 'SERVICE_OVERVIEW_PAGE_LOADED',
  PAYMENT_DETAILS_UPDATE: 'PAYMENT_DETAILS_UPDATE',
  ACCOUNT_PAYMENT_EDIT_LOADED: 'ACCOUNT_PAYMENT_EDIT_LOADED',

  MEMBER_DISCOUNTS_PAGE_LOADED: 'MEMBER_DISCOUNTS_PAGE_LOADED',

  PAYMENT_HISTORY_PAGE_LOADED: 'PAYMENT_HISTORY_PAGE_LOADED',

  // service actions
  UPDATE_SERVICE_DETAILS: 'UPDATE_SERVICE_DETAILS'
};
